name: Get Messages

on:
  workflow_dispatch:


jobs:
  fetch-messages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eolab-hsrw/easy-px4:ubuntu-22.04
    permissions:
      contents: write 
    strategy:
      fail-fast: false
      matrix:
        drone: ['protofyer', 'condor']
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Configure Git committer
        run: |
          git config --global user.email "github-actions[bot]"
          git config --global user.name "GitHub Actions Bot"
      - name: install tool eolab-drones
        run: |
         pip install git+https://github.com/EOLab-HSRW/drones-fw.git@main#egg=eolab_drones
      - name: checkout to drone branch
        run: |
          git checkout -B "${{ matrix.drone }}"
      - name: collect msg using eolab-tool
        run: | 
          DEBUG=1 eolab_drones build --type sitl --drone ${{ matrix.drone }} --skip-compilation --msgs-output ../px4_msgs
      - name: commit changes and push
        run: | 
         git add .
         git commit -m "Sync messages"
         git push -f origin ${{ matrix.drone }}  
