name: Get Messages

on:
  workflow_dispatch:


jobs:
  fetch-messages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eolab-hsrw/easy-px4:ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        drone: ['drone1', 'drone2']
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: directory ls
        run: ls
      - name: check drone branch
        run: |
          echo "${{ matrix.drone }}"
      - name: install tool eolab-drones
        run: |
         pip install git+https://github.com/EOLab-HSRW/drones-fw.git@main#egg=eolab_drones

